### ISSUE TITLE
No command "N4BiasFieldCorrection" found on host kim-X10DAi. Please check that the corresponding package is installed.

### ISSUE THREAD

**Issue by wky1998** [bigbigbean/N4BiasFieldCorrection#1]
thanks for your answer, i just installed ANTs，but i don't understand why it still error 
No command "N4BiasFieldCorrection" found on host kim-X10DAi. Please check that the corresponding package is installed.

**Comment by bigbigbean** [comment]
Only SimpleITK is needed to run this code. 
You can install SimpleITK by this code:
`pip install SimpleITK`
