### ISSUE TITLE
How is your parameter set to get the result of picture 1

### ISSUE THREAD

**Issue by serenityd** [bigbigbean/N4BiasFieldCorrection#2]
I tried different parameter settings, but the resulting image and the original image change are not very noticeable.

**Comment by bigbigbean** [comment]
The parameter setting I used was the same as the code attached. 
`maskImage = sitk.OtsuThreshold(inputImage,0,1,200)`
If this method do not show good result on your images, you can try other image preprocessing methods, like histogram equlization, Contrast Limited Adaptive histgram equalization(CLAHE) etc.
